version: '3'

services:
  master:
    image: locustio/locust:latest
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://chi:3000
    networks:
      - load-test-api

  worker:
    image: locustio/locust:latest
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    networks:
      - load-test-api

networks:
  load-test-api:
    external:
      name: api-ntw