version: '3'

services:
  master:
    image: locustio/locust:latest
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H 127.0.0.1:8080

  worker:
    image: locustio/locust:latest
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master