version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./load_test/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H localhost:8080

  worker:
    image: locustio/locust
    volumes:
      - ./load_test/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master